name: shimmer_loading_placeholder
description: "A Flutter package that provides a customizable shimmer loading effect for placeholders, enhancing the user experience during data loading."
version: 1.0.0
homepage: https://github.com/toychibayev/package_shimmer
repository: https://github.com/toychibayev/package_shimmer

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

example:
  path: example/